# Generated by Django 3.0.2 on 2020-03-20 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('hazard_feed', '0011_rss_feed_url_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecipients',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EmailActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('76811883-d216-4340-a27a-18dc0209fdf6'), primary_key=True, serialize=False)),
                ('code', models.CharField(default=51635961, editable=False, max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hazard_feed.WeatherRecipients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
