# Generated by Django 3.0.2 on 2020-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_feed', '0012_auto_20200228_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecipients',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
