# Generated by Django 3.0.2 on 2020-03-18 22:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('hazard_feed', '0013_auto_20200228_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherrecipients',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherrecipients',
            name='date_modified',
        ),
        migrations.CreateModel(
            name='EmailActivationCodeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ede6d7d9-d5fd-4513-b217-adc094967ac3'), primary_key=True, serialize=False)),
                ('code', models.CharField(default=27411029, editable=False, max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hazard_feed.WeatherRecipients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
