# Generated by Django 3.0.2 on 2020-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_feed', '0013_auto_20200228_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivationCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=75837281, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='weatherrecipients',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherrecipients',
            name='date_modified',
        ),
    ]
