# Generated by Django 3.0.2 on 2020-03-16 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('hazard_feed', '0014_auto_20200315_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivationcodemodel',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AddField(
            model_name='emailactivationcodemodel',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hazard_feed.WeatherRecipients'),
        ),
        migrations.AlterField(
            model_name='emailactivationcodemodel',
            name='code',
            field=models.UUIDField(default=44107150, editable=False),
        ),
        migrations.AlterField(
            model_name='emailactivationcodemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c1155f2-322e-44a1-a9e0-f5b7271f262b'), primary_key=True, serialize=False),
        ),
    ]
