# Generated by Django 3.0.2 on 2020-03-18 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_feed', '0015_auto_20200316_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivationcodemodel',
            name='code',
            field=models.CharField(default=43464496, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='emailactivationcodemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e63e98bf-5c06-4dc4-8db1-8f6d1b4485b1'), primary_key=True, serialize=False),
        ),
    ]
