# Generated by Django 3.0.2 on 2020-03-18 13:41

from django.db import migrations, models
import hazard_feed.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_feed', '0016_auto_20200318_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivationcodemodel',
            name='code',
            field=models.CharField(default=hazard_feed.models.gen_act_code, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='emailactivationcodemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
