# Generated by Django 3.0.2 on 2020-10-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_feed', '0017_weatherrecipients_hazard_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecipients',
            name='hazard_levels',
            field=models.ManyToManyField(null=True, to='hazard_feed.HazardLevels'),
        ),
    ]
