# Generated by Django 3.0.2 on 2020-11-03 18:37

from django.db import migrations, models
import django.db.models.deletion
import hazard_feed.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_feed', '0018_weatherrecipientseditcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditValidationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(default=hazard_feed.models.gen_act_code, editable=False, max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hazard_feed.WeatherRecipientsEditCandidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
